CREATE TABLE PRODUCT( 
	ID BIGINT AUTO_INCREMENT, 
	NAME VARCHAR(30), 
	DESCRIPTION VARCHAR(150), 
	CATEGORY VARCHAR(15), 
	COST DECIMAL(20,2), 
	DISCOUNT BOOL NOT NULL DEFAULT '0', 
	PRIMARY KEY(ID) 
);

CREATE TABLE LOCATION( 
 	PRODUCT_ID BIGINT, 
 	LOCATION VARCHAR(15),  
 	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) 
 	    ON DELETE CASCADE ON UPDATE CASCADE
 );
 
CREATE TABLE PURCHASE_ORDER( 
	ID BIGINT AUTO_INCREMENT, 
	TOTAL_COST DECIMAL(20,2), 
	PRIMARY KEY(ID)
);

CREATE TABLE ORDER_ITEM(
	ID BIGINT AUTO_INCREMENT, 
	PRODUCT_ID BIGINT, 
	PURCHASE_ORDER_ID BIGINT,
	DISCOUNT_PRICE DECIMAL(20,2), 
	PRIMARY KEY (ID), 
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
	    ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES PURCHASE_ORDER(ID)
	    ON DELETE CASCADE ON UPDATE CASCADE
);

drop table LOCATION;
drop table ORDER_ITEM;
drop table PURCHASE_ORDER;
drop table PRODUCT;



